project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"

execute:
  freeze: auto
  engine: knitr

website:
  title: "Liqing Li"
  site-url: "https://www.liqing-li.com"
  description: "Liqing Li — Assistant Professor, Department of Agricultural Economics, Texas A&M University"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: cv.qmd
        text: CV
      - href: teaching.qmd
        text: Teaching
      - href: contact.qmd
        text: Contact
    right:
      - icon: envelope
        href: mailto:liqing.li@ag.tamu.edu
      - icon: github
        href: https://github.com/Liqing-Li
      - icon: mortarboard-fill
        href: https://scholar.google.com/citations?user=IzxcQdMAAAAJ&hl=en
        text: "Google Scholar"
  page-footer:
    center: "© 2026 Liqing Li"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    grid:
      body-width: 850px
